import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.model_zoo import load_url


__all__ = ['BNInception', 'bninception']


model_urls = {
    'bninception': 'http://data.lip6.fr/cadene/pretrainedmodels/bn_inception-52deb4733.pth'}


class BNInception(nn.Module):
    RGB_MEAN = [128, 117, 104]
    RGB_STD = [1, 1, 1]

    def __init__(self, num_classes=None, norm_layer=None):
        super(BNInception, self).__init__()
        self.num_classes = num_classes
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        self.conv1_7x7_s2 = nn.Conv2d(3, 64, 7, 2, padding=3)
        self.conv1_7x7_s2_bn = norm_layer(64)
        self.conv1_relu_7x7 = nn.ReLU(inplace=True)
        self.pool1_3x3_s2 = nn.MaxPool2d(3, 2, dilation=1, ceil_mode=True)
        self.conv2_3x3_reduce = nn.Conv2d(64, 64, 1, 1)
        self.conv2_3x3_reduce_bn = norm_layer(64)
        self.conv2_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.conv2_3x3 = nn.Conv2d(64, 192, 3, 1, padding=1)
        self.conv2_3x3_bn = norm_layer(192)
        self.conv2_relu_3x3 = nn.ReLU(inplace=True)
        self.pool2_3x3_s2 = nn.MaxPool2d(3, 2, dilation=1, ceil_mode=True)
        self.inception_3a_1x1 = nn.Conv2d(192, 64, 1, 1)
        self.inception_3a_1x1_bn = norm_layer(64)
        self.inception_3a_relu_1x1 = nn.ReLU(inplace=True)
        self.inception_3a_3x3_reduce = nn.Conv2d(192, 64, 1, 1)
        self.inception_3a_3x3_reduce_bn = norm_layer(64)
        self.inception_3a_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_3a_3x3 = nn.Conv2d(64, 64, 3, 1, padding=1)
        self.inception_3a_3x3_bn = norm_layer(64)
        self.inception_3a_relu_3x3 = nn.ReLU(inplace=True)
        self.inception_3a_double_3x3_reduce = nn.Conv2d(192, 64, 1, 1)
        self.inception_3a_double_3x3_reduce_bn = norm_layer(64)
        self.inception_3a_relu_double_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_3a_double_3x3_1 = nn.Conv2d(64, 96, 3, 1, padding=1)
        self.inception_3a_double_3x3_1_bn = norm_layer(96)
        self.inception_3a_relu_double_3x3_1 = nn.ReLU(inplace=True)
        self.inception_3a_double_3x3_2 = nn.Conv2d(96, 96, 3, 1, padding=1)
        self.inception_3a_double_3x3_2_bn = norm_layer(96)
        self.inception_3a_relu_double_3x3_2 = nn.ReLU(inplace=True)
        self.inception_3a_pool = nn.AvgPool2d(3, 1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_3a_pool_proj = nn.Conv2d(192, 32, 1, 1)
        self.inception_3a_pool_proj_bn = norm_layer(32)
        self.inception_3a_relu_pool_proj = nn.ReLU(inplace=True)
        self.inception_3b_1x1 = nn.Conv2d(256, 64, 1, 1)
        self.inception_3b_1x1_bn = norm_layer(64)
        self.inception_3b_relu_1x1 = nn.ReLU(inplace=True)
        self.inception_3b_3x3_reduce = nn.Conv2d(256, 64, 1, 1)
        self.inception_3b_3x3_reduce_bn = norm_layer(64)
        self.inception_3b_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_3b_3x3 = nn.Conv2d(64, 96, 3, 1, padding=1)
        self.inception_3b_3x3_bn = norm_layer(96)
        self.inception_3b_relu_3x3 = nn.ReLU(inplace=True)
        self.inception_3b_double_3x3_reduce = nn.Conv2d(256, 64, 1, 1)
        self.inception_3b_double_3x3_reduce_bn = norm_layer(64)
        self.inception_3b_relu_double_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_3b_double_3x3_1 = nn.Conv2d(64, 96, 3, 1, padding=1)
        self.inception_3b_double_3x3_1_bn = norm_layer(96)
        self.inception_3b_relu_double_3x3_1 = nn.ReLU(inplace=True)
        self.inception_3b_double_3x3_2 = nn.Conv2d(96, 96, 3, 1, padding=1)
        self.inception_3b_double_3x3_2_bn = norm_layer(96)
        self.inception_3b_relu_double_3x3_2 = nn.ReLU(inplace=True)
        self.inception_3b_pool = nn.AvgPool2d(3, 1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_3b_pool_proj = nn.Conv2d(256, 64, 1, 1)
        self.inception_3b_pool_proj_bn = norm_layer(64)
        self.inception_3b_relu_pool_proj = nn.ReLU(inplace=True)
        self.inception_3c_3x3_reduce = nn.Conv2d(320, 128, 1, 1)
        self.inception_3c_3x3_reduce_bn = norm_layer(128)
        self.inception_3c_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_3c_3x3 = nn.Conv2d(128, 160, 3, 2, padding=1)
        self.inception_3c_3x3_bn = norm_layer(160)
        self.inception_3c_relu_3x3 = nn.ReLU(inplace=True)
        self.inception_3c_double_3x3_reduce = nn.Conv2d(320, 64, 1, 1)
        self.inception_3c_double_3x3_reduce_bn = norm_layer(64)
        self.inception_3c_relu_double_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_3c_double_3x3_1 = nn.Conv2d(64, 96, 3, 1, padding=1)
        self.inception_3c_double_3x3_1_bn = norm_layer(96)
        self.inception_3c_relu_double_3x3_1 = nn.ReLU(inplace=True)
        self.inception_3c_double_3x3_2 = nn.Conv2d(96, 96, 3, 2, padding=1)
        self.inception_3c_double_3x3_2_bn = norm_layer(96)
        self.inception_3c_relu_double_3x3_2 = nn.ReLU(inplace=True)
        self.inception_3c_pool = nn.MaxPool2d(3, 2, dilation=1, ceil_mode=True)
        self.inception_4a_1x1 = nn.Conv2d(576, 224, 1, 1)
        self.inception_4a_1x1_bn = norm_layer(224)
        self.inception_4a_relu_1x1 = nn.ReLU(inplace=True)
        self.inception_4a_3x3_reduce = nn.Conv2d(576, 64, 1, 1)
        self.inception_4a_3x3_reduce_bn = norm_layer(64)
        self.inception_4a_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_4a_3x3 = nn.Conv2d(64, 96, 3, 1, padding=1)
        self.inception_4a_3x3_bn = norm_layer(96)
        self.inception_4a_relu_3x3 = nn.ReLU(inplace=True)
        self.inception_4a_double_3x3_reduce = nn.Conv2d(576, 96, 1, 1)
        self.inception_4a_double_3x3_reduce_bn = norm_layer(96)
        self.inception_4a_relu_double_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_4a_double_3x3_1 = nn.Conv2d(96, 128, 3, 1, padding=1)
        self.inception_4a_double_3x3_1_bn = norm_layer(128)
        self.inception_4a_relu_double_3x3_1 = nn.ReLU(inplace=True)
        self.inception_4a_double_3x3_2 = nn.Conv2d(128, 128, 3, 1, padding=1)
        self.inception_4a_double_3x3_2_bn = norm_layer(128)
        self.inception_4a_relu_double_3x3_2 = nn.ReLU(inplace=True)
        self.inception_4a_pool = nn.AvgPool2d(3, 1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_4a_pool_proj = nn.Conv2d(576, 128, 1, 1)
        self.inception_4a_pool_proj_bn = norm_layer(128)
        self.inception_4a_relu_pool_proj = nn.ReLU(inplace=True)
        self.inception_4b_1x1 = nn.Conv2d(576, 192, 1, 1)
        self.inception_4b_1x1_bn = norm_layer(192)
        self.inception_4b_relu_1x1 = nn.ReLU(inplace=True)
        self.inception_4b_3x3_reduce = nn.Conv2d(576, 96, 1, 1)
        self.inception_4b_3x3_reduce_bn = norm_layer(96)
        self.inception_4b_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_4b_3x3 = nn.Conv2d(96, 128, 3, 1, padding=1)
        self.inception_4b_3x3_bn = norm_layer(128)
        self.inception_4b_relu_3x3 = nn.ReLU(inplace=True)
        self.inception_4b_double_3x3_reduce = nn.Conv2d(576, 96, 1, 1)
        self.inception_4b_double_3x3_reduce_bn = norm_layer(96)
        self.inception_4b_relu_double_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_4b_double_3x3_1 = nn.Conv2d(96, 128, 3, 1, padding=1)
        self.inception_4b_double_3x3_1_bn = norm_layer(128)
        self.inception_4b_relu_double_3x3_1 = nn.ReLU(inplace=True)
        self.inception_4b_double_3x3_2 = nn.Conv2d(128, 128, 3, 1, padding=1)
        self.inception_4b_double_3x3_2_bn = norm_layer(128)
        self.inception_4b_relu_double_3x3_2 = nn.ReLU(inplace=True)
        self.inception_4b_pool = nn.AvgPool2d(3, 1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_4b_pool_proj = nn.Conv2d(576, 128, 1, 1)
        self.inception_4b_pool_proj_bn = norm_layer(128)
        self.inception_4b_relu_pool_proj = nn.ReLU(inplace=True)
        self.inception_4c_1x1 = nn.Conv2d(576, 160, 1, 1)
        self.inception_4c_1x1_bn = norm_layer(160)
        self.inception_4c_relu_1x1 = nn.ReLU(inplace=True)
        self.inception_4c_3x3_reduce = nn.Conv2d(576, 128, 1, 1)
        self.inception_4c_3x3_reduce_bn = norm_layer(128)
        self.inception_4c_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_4c_3x3 = nn.Conv2d(128, 160, 3, 1, padding=1)
        self.inception_4c_3x3_bn = norm_layer(160)
        self.inception_4c_relu_3x3 = nn.ReLU(inplace=True)
        self.inception_4c_double_3x3_reduce = nn.Conv2d(576, 128, 1, 1)
        self.inception_4c_double_3x3_reduce_bn = norm_layer(128)
        self.inception_4c_relu_double_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_4c_double_3x3_1 = nn.Conv2d(128, 160, 3, 1, padding=1)
        self.inception_4c_double_3x3_1_bn = norm_layer(160)
        self.inception_4c_relu_double_3x3_1 = nn.ReLU(inplace=True)
        self.inception_4c_double_3x3_2 = nn.Conv2d(160, 160, 3, 1, padding=1)
        self.inception_4c_double_3x3_2_bn = norm_layer(160)
        self.inception_4c_relu_double_3x3_2 = nn.ReLU(inplace=True)
        self.inception_4c_pool = nn.AvgPool2d(3, 1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_4c_pool_proj = nn.Conv2d(576, 128, 1, 1)
        self.inception_4c_pool_proj_bn = norm_layer(128)
        self.inception_4c_relu_pool_proj = nn.ReLU(inplace=True)
        self.inception_4d_1x1 = nn.Conv2d(608, 96, 1, 1)
        self.inception_4d_1x1_bn = norm_layer(96)
        self.inception_4d_relu_1x1 = nn.ReLU(inplace=True)
        self.inception_4d_3x3_reduce = nn.Conv2d(608, 128, 1, 1)
        self.inception_4d_3x3_reduce_bn = norm_layer(128)
        self.inception_4d_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_4d_3x3 = nn.Conv2d(128, 192, 3, 1, padding=1)
        self.inception_4d_3x3_bn = norm_layer(192)
        self.inception_4d_relu_3x3 = nn.ReLU(inplace=True)
        self.inception_4d_double_3x3_reduce = nn.Conv2d(608, 160, 1, 1)
        self.inception_4d_double_3x3_reduce_bn = norm_layer(160)
        self.inception_4d_relu_double_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_4d_double_3x3_1 = nn.Conv2d(160, 192, 3, 1, padding=1)
        self.inception_4d_double_3x3_1_bn = norm_layer(192)
        self.inception_4d_relu_double_3x3_1 = nn.ReLU(inplace=True)
        self.inception_4d_double_3x3_2 = nn.Conv2d(192, 192, 3, 1, padding=1)
        self.inception_4d_double_3x3_2_bn = norm_layer(192)
        self.inception_4d_relu_double_3x3_2 = nn.ReLU(inplace=True)
        self.inception_4d_pool = nn.AvgPool2d(3, 1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_4d_pool_proj = nn.Conv2d(608, 128, 1, 1)
        self.inception_4d_pool_proj_bn = norm_layer(128)
        self.inception_4d_relu_pool_proj = nn.ReLU(inplace=True)
        self.inception_4e_3x3_reduce = nn.Conv2d(608, 128, 1, 1)
        self.inception_4e_3x3_reduce_bn = norm_layer(128)
        self.inception_4e_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_4e_3x3 = nn.Conv2d(128, 192, 3, 2, padding=1)
        self.inception_4e_3x3_bn = norm_layer(192)
        self.inception_4e_relu_3x3 = nn.ReLU(inplace=True)
        self.inception_4e_double_3x3_reduce = nn.Conv2d(608, 192, 1, 1)
        self.inception_4e_double_3x3_reduce_bn = norm_layer(192)
        self.inception_4e_relu_double_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_4e_double_3x3_1 = nn.Conv2d(192, 256, 3, 1, padding=1)
        self.inception_4e_double_3x3_1_bn = norm_layer(256)
        self.inception_4e_relu_double_3x3_1 = nn.ReLU(inplace=True)
        self.inception_4e_double_3x3_2 = nn.Conv2d(256, 256, 3, 2, padding=1)
        self.inception_4e_double_3x3_2_bn = norm_layer(256)
        self.inception_4e_relu_double_3x3_2 = nn.ReLU(inplace=True)
        self.inception_4e_pool = nn.MaxPool2d(3, 2, dilation=1, ceil_mode=True)
        self.inception_5a_1x1 = nn.Conv2d(1056, 352, 1, 1)
        self.inception_5a_1x1_bn = norm_layer(352)
        self.inception_5a_relu_1x1 = nn.ReLU(inplace=True)
        self.inception_5a_3x3_reduce = nn.Conv2d(1056, 192, 1, 1)
        self.inception_5a_3x3_reduce_bn = norm_layer(192)
        self.inception_5a_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_5a_3x3 = nn.Conv2d(192, 320, 3, 1, padding=1)
        self.inception_5a_3x3_bn = norm_layer(320)
        self.inception_5a_relu_3x3 = nn.ReLU(inplace=True)
        self.inception_5a_double_3x3_reduce = nn.Conv2d(1056, 160, 1, 1)
        self.inception_5a_double_3x3_reduce_bn = norm_layer(160)
        self.inception_5a_relu_double_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_5a_double_3x3_1 = nn.Conv2d(160, 224, 3, 1, padding=1)
        self.inception_5a_double_3x3_1_bn = norm_layer(224)
        self.inception_5a_relu_double_3x3_1 = nn.ReLU(inplace=True)
        self.inception_5a_double_3x3_2 = nn.Conv2d(224, 224, 3, 1, padding=1)
        self.inception_5a_double_3x3_2_bn = norm_layer(224)
        self.inception_5a_relu_double_3x3_2 = nn.ReLU(inplace=True)
        self.inception_5a_pool = nn.AvgPool2d(3, 1, padding=1, ceil_mode=True, count_include_pad=True)
        self.inception_5a_pool_proj = nn.Conv2d(1056, 128, 1, 1)
        self.inception_5a_pool_proj_bn = norm_layer(128)
        self.inception_5a_relu_pool_proj = nn.ReLU(inplace=True)
        self.inception_5b_1x1 = nn.Conv2d(1024, 352, 1, 1)
        self.inception_5b_1x1_bn = norm_layer(352)
        self.inception_5b_relu_1x1 = nn.ReLU(inplace=True)
        self.inception_5b_3x3_reduce = nn.Conv2d(1024, 192, 1, 1)
        self.inception_5b_3x3_reduce_bn = norm_layer(192)
        self.inception_5b_relu_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_5b_3x3 = nn.Conv2d(192, 320, 3, 1, padding=1)
        self.inception_5b_3x3_bn = norm_layer(320)
        self.inception_5b_relu_3x3 = nn.ReLU(inplace=True)
        self.inception_5b_double_3x3_reduce = nn.Conv2d(1024, 192, 1, 1)
        self.inception_5b_double_3x3_reduce_bn = norm_layer(192)
        self.inception_5b_relu_double_3x3_reduce = nn.ReLU(inplace=True)
        self.inception_5b_double_3x3_1 = nn.Conv2d(192, 224, 3, 1, padding=1)
        self.inception_5b_double_3x3_1_bn = norm_layer(224)
        self.inception_5b_relu_double_3x3_1 = nn.ReLU(inplace=True)
        self.inception_5b_double_3x3_2 = nn.Conv2d(224, 224, 3, 1, padding=1)
        self.inception_5b_double_3x3_2_bn = norm_layer(224)
        self.inception_5b_relu_double_3x3_2 = nn.ReLU(inplace=True)
        self.inception_5b_pool = nn.MaxPool2d(3, 1, padding=1, dilation=1, ceil_mode=True)
        self.inception_5b_pool_proj = nn.Conv2d(1024, 128, 1, 1)
        self.inception_5b_pool_proj_bn = norm_layer(128)
        self.inception_5b_relu_pool_proj = nn.ReLU(inplace=True)
        if num_classes is not None:
            self.last_linear = nn.Linear(1024, num_classes)
        else:
            self.last_linear = None

    def features(self, x):
        conv1_7x7_s2_out = self.conv1_7x7_s2(x)
        conv1_7x7_s2_bn_out = self.conv1_7x7_s2_bn(conv1_7x7_s2_out)
        conv1_relu_7x7_out = self.conv1_relu_7x7(conv1_7x7_s2_bn_out)
        pool1_3x3_s2_out = self.pool1_3x3_s2(conv1_relu_7x7_out)
        conv2_3x3_reduce_out = self.conv2_3x3_reduce(pool1_3x3_s2_out)
        conv2_3x3_reduce_bn_out = self.conv2_3x3_reduce_bn(conv2_3x3_reduce_out)
        conv2_relu_3x3_reduce_out = self.conv2_relu_3x3_reduce(conv2_3x3_reduce_bn_out)
        conv2_3x3_out = self.conv2_3x3(conv2_relu_3x3_reduce_out)
        conv2_3x3_bn_out = self.conv2_3x3_bn(conv2_3x3_out)
        conv2_relu_3x3_out = self.conv2_relu_3x3(conv2_3x3_bn_out)
        pool2_3x3_s2_out = self.pool2_3x3_s2(conv2_relu_3x3_out)
        inception_3a_1x1_out = self.inception_3a_1x1(pool2_3x3_s2_out)
        inception_3a_1x1_bn_out = self.inception_3a_1x1_bn(inception_3a_1x1_out)
        inception_3a_relu_1x1_out = self.inception_3a_relu_1x1(inception_3a_1x1_bn_out)
        inception_3a_3x3_reduce_out = self.inception_3a_3x3_reduce(pool2_3x3_s2_out)
        inception_3a_3x3_reduce_bn_out = self.inception_3a_3x3_reduce_bn(inception_3a_3x3_reduce_out)
        inception_3a_relu_3x3_reduce_out = self.inception_3a_relu_3x3_reduce(inception_3a_3x3_reduce_bn_out)
        inception_3a_3x3_out = self.inception_3a_3x3(inception_3a_relu_3x3_reduce_out)
        inception_3a_3x3_bn_out = self.inception_3a_3x3_bn(inception_3a_3x3_out)
        inception_3a_relu_3x3_out = self.inception_3a_relu_3x3(inception_3a_3x3_bn_out)
        inception_3a_double_3x3_reduce_out = self.inception_3a_double_3x3_reduce(pool2_3x3_s2_out)
        inception_3a_double_3x3_reduce_bn_out = self.inception_3a_double_3x3_reduce_bn(inception_3a_double_3x3_reduce_out)
        inception_3a_relu_double_3x3_reduce_out = self.inception_3a_relu_double_3x3_reduce(inception_3a_double_3x3_reduce_bn_out)
        inception_3a_double_3x3_1_out = self.inception_3a_double_3x3_1(inception_3a_relu_double_3x3_reduce_out)
        inception_3a_double_3x3_1_bn_out = self.inception_3a_double_3x3_1_bn(inception_3a_double_3x3_1_out)
        inception_3a_relu_double_3x3_1_out = self.inception_3a_relu_double_3x3_1(inception_3a_double_3x3_1_bn_out)
        inception_3a_double_3x3_2_out = self.inception_3a_double_3x3_2(inception_3a_relu_double_3x3_1_out)
        inception_3a_double_3x3_2_bn_out = self.inception_3a_double_3x3_2_bn(inception_3a_double_3x3_2_out)
        inception_3a_relu_double_3x3_2_out = self.inception_3a_relu_double_3x3_2(inception_3a_double_3x3_2_bn_out)
        inception_3a_pool_out = self.inception_3a_pool(pool2_3x3_s2_out)
        inception_3a_pool_proj_out = self.inception_3a_pool_proj(inception_3a_pool_out)
        inception_3a_pool_proj_bn_out = self.inception_3a_pool_proj_bn(inception_3a_pool_proj_out)
        inception_3a_relu_pool_proj_out = self.inception_3a_relu_pool_proj(inception_3a_pool_proj_bn_out)
        inception_3a_output_out = torch.cat([inception_3a_relu_1x1_out,inception_3a_relu_3x3_out,inception_3a_relu_double_3x3_2_out ,inception_3a_relu_pool_proj_out], 1)
        inception_3b_1x1_out = self.inception_3b_1x1(inception_3a_output_out)
        inception_3b_1x1_bn_out = self.inception_3b_1x1_bn(inception_3b_1x1_out)
        inception_3b_relu_1x1_out = self.inception_3b_relu_1x1(inception_3b_1x1_bn_out)
        inception_3b_3x3_reduce_out = self.inception_3b_3x3_reduce(inception_3a_output_out)
        inception_3b_3x3_reduce_bn_out = self.inception_3b_3x3_reduce_bn(inception_3b_3x3_reduce_out)
        inception_3b_relu_3x3_reduce_out = self.inception_3b_relu_3x3_reduce(inception_3b_3x3_reduce_bn_out)
        inception_3b_3x3_out = self.inception_3b_3x3(inception_3b_relu_3x3_reduce_out)
        inception_3b_3x3_bn_out = self.inception_3b_3x3_bn(inception_3b_3x3_out)
        inception_3b_relu_3x3_out = self.inception_3b_relu_3x3(inception_3b_3x3_bn_out)
        inception_3b_double_3x3_reduce_out = self.inception_3b_double_3x3_reduce(inception_3a_output_out)
        inception_3b_double_3x3_reduce_bn_out = self.inception_3b_double_3x3_reduce_bn(inception_3b_double_3x3_reduce_out)
        inception_3b_relu_double_3x3_reduce_out = self.inception_3b_relu_double_3x3_reduce(inception_3b_double_3x3_reduce_bn_out)
        inception_3b_double_3x3_1_out = self.inception_3b_double_3x3_1(inception_3b_relu_double_3x3_reduce_out)
        inception_3b_double_3x3_1_bn_out = self.inception_3b_double_3x3_1_bn(inception_3b_double_3x3_1_out)
        inception_3b_relu_double_3x3_1_out = self.inception_3b_relu_double_3x3_1(inception_3b_double_3x3_1_bn_out)
        inception_3b_double_3x3_2_out = self.inception_3b_double_3x3_2(inception_3b_relu_double_3x3_1_out)
        inception_3b_double_3x3_2_bn_out = self.inception_3b_double_3x3_2_bn(inception_3b_double_3x3_2_out)
        inception_3b_relu_double_3x3_2_out = self.inception_3b_relu_double_3x3_2(inception_3b_double_3x3_2_bn_out)
        inception_3b_pool_out = self.inception_3b_pool(inception_3a_output_out)
        inception_3b_pool_proj_out = self.inception_3b_pool_proj(inception_3b_pool_out)
        inception_3b_pool_proj_bn_out = self.inception_3b_pool_proj_bn(inception_3b_pool_proj_out)
        inception_3b_relu_pool_proj_out = self.inception_3b_relu_pool_proj(inception_3b_pool_proj_bn_out)
        inception_3b_output_out = torch.cat([inception_3b_relu_1x1_out,inception_3b_relu_3x3_out,inception_3b_relu_double_3x3_2_out,inception_3b_relu_pool_proj_out], 1)
        inception_3c_3x3_reduce_out = self.inception_3c_3x3_reduce(inception_3b_output_out)
        inception_3c_3x3_reduce_bn_out = self.inception_3c_3x3_reduce_bn(inception_3c_3x3_reduce_out)
        inception_3c_relu_3x3_reduce_out = self.inception_3c_relu_3x3_reduce(inception_3c_3x3_reduce_bn_out)
        inception_3c_3x3_out = self.inception_3c_3x3(inception_3c_relu_3x3_reduce_out)
        inception_3c_3x3_bn_out = self.inception_3c_3x3_bn(inception_3c_3x3_out)
        inception_3c_relu_3x3_out = self.inception_3c_relu_3x3(inception_3c_3x3_bn_out)
        inception_3c_double_3x3_reduce_out = self.inception_3c_double_3x3_reduce(inception_3b_output_out)
        inception_3c_double_3x3_reduce_bn_out = self.inception_3c_double_3x3_reduce_bn(inception_3c_double_3x3_reduce_out)
        inception_3c_relu_double_3x3_reduce_out = self.inception_3c_relu_double_3x3_reduce(inception_3c_double_3x3_reduce_bn_out)
        inception_3c_double_3x3_1_out = self.inception_3c_double_3x3_1(inception_3c_relu_double_3x3_reduce_out)
        inception_3c_double_3x3_1_bn_out = self.inception_3c_double_3x3_1_bn(inception_3c_double_3x3_1_out)
        inception_3c_relu_double_3x3_1_out = self.inception_3c_relu_double_3x3_1(inception_3c_double_3x3_1_bn_out)
        inception_3c_double_3x3_2_out = self.inception_3c_double_3x3_2(inception_3c_relu_double_3x3_1_out)
        inception_3c_double_3x3_2_bn_out = self.inception_3c_double_3x3_2_bn(inception_3c_double_3x3_2_out)
        inception_3c_relu_double_3x3_2_out = self.inception_3c_relu_double_3x3_2(inception_3c_double_3x3_2_bn_out)
        inception_3c_pool_out = self.inception_3c_pool(inception_3b_output_out)
        inception_3c_output_out = torch.cat([inception_3c_relu_3x3_out,inception_3c_relu_double_3x3_2_out,inception_3c_pool_out], 1)
        inception_4a_1x1_out = self.inception_4a_1x1(inception_3c_output_out)
        inception_4a_1x1_bn_out = self.inception_4a_1x1_bn(inception_4a_1x1_out)
        inception_4a_relu_1x1_out = self.inception_4a_relu_1x1(inception_4a_1x1_bn_out)
        inception_4a_3x3_reduce_out = self.inception_4a_3x3_reduce(inception_3c_output_out)
        inception_4a_3x3_reduce_bn_out = self.inception_4a_3x3_reduce_bn(inception_4a_3x3_reduce_out)
        inception_4a_relu_3x3_reduce_out = self.inception_4a_relu_3x3_reduce(inception_4a_3x3_reduce_bn_out)
        inception_4a_3x3_out = self.inception_4a_3x3(inception_4a_relu_3x3_reduce_out)
        inception_4a_3x3_bn_out = self.inception_4a_3x3_bn(inception_4a_3x3_out)
        inception_4a_relu_3x3_out = self.inception_4a_relu_3x3(inception_4a_3x3_bn_out)
        inception_4a_double_3x3_reduce_out = self.inception_4a_double_3x3_reduce(inception_3c_output_out)
        inception_4a_double_3x3_reduce_bn_out = self.inception_4a_double_3x3_reduce_bn(inception_4a_double_3x3_reduce_out)
        inception_4a_relu_double_3x3_reduce_out = self.inception_4a_relu_double_3x3_reduce(inception_4a_double_3x3_reduce_bn_out)
        inception_4a_double_3x3_1_out = self.inception_4a_double_3x3_1(inception_4a_relu_double_3x3_reduce_out)
        inception_4a_double_3x3_1_bn_out = self.inception_4a_double_3x3_1_bn(inception_4a_double_3x3_1_out)
        inception_4a_relu_double_3x3_1_out = self.inception_4a_relu_double_3x3_1(inception_4a_double_3x3_1_bn_out)
        inception_4a_double_3x3_2_out = self.inception_4a_double_3x3_2(inception_4a_relu_double_3x3_1_out)
        inception_4a_double_3x3_2_bn_out = self.inception_4a_double_3x3_2_bn(inception_4a_double_3x3_2_out)
        inception_4a_relu_double_3x3_2_out = self.inception_4a_relu_double_3x3_2(inception_4a_double_3x3_2_bn_out)
        inception_4a_pool_out = self.inception_4a_pool(inception_3c_output_out)
        inception_4a_pool_proj_out = self.inception_4a_pool_proj(inception_4a_pool_out)
        inception_4a_pool_proj_bn_out = self.inception_4a_pool_proj_bn(inception_4a_pool_proj_out)
        inception_4a_relu_pool_proj_out = self.inception_4a_relu_pool_proj(inception_4a_pool_proj_bn_out)
        inception_4a_output_out = torch.cat([inception_4a_relu_1x1_out,inception_4a_relu_3x3_out,inception_4a_relu_double_3x3_2_out,inception_4a_relu_pool_proj_out], 1)
        inception_4b_1x1_out = self.inception_4b_1x1(inception_4a_output_out)
        inception_4b_1x1_bn_out = self.inception_4b_1x1_bn(inception_4b_1x1_out)
        inception_4b_relu_1x1_out = self.inception_4b_relu_1x1(inception_4b_1x1_bn_out)
        inception_4b_3x3_reduce_out = self.inception_4b_3x3_reduce(inception_4a_output_out)
        inception_4b_3x3_reduce_bn_out = self.inception_4b_3x3_reduce_bn(inception_4b_3x3_reduce_out)
        inception_4b_relu_3x3_reduce_out = self.inception_4b_relu_3x3_reduce(inception_4b_3x3_reduce_bn_out)
        inception_4b_3x3_out = self.inception_4b_3x3(inception_4b_relu_3x3_reduce_out)
        inception_4b_3x3_bn_out = self.inception_4b_3x3_bn(inception_4b_3x3_out)
        inception_4b_relu_3x3_out = self.inception_4b_relu_3x3(inception_4b_3x3_bn_out)
        inception_4b_double_3x3_reduce_out = self.inception_4b_double_3x3_reduce(inception_4a_output_out)
        inception_4b_double_3x3_reduce_bn_out = self.inception_4b_double_3x3_reduce_bn(inception_4b_double_3x3_reduce_out)
        inception_4b_relu_double_3x3_reduce_out = self.inception_4b_relu_double_3x3_reduce(inception_4b_double_3x3_reduce_bn_out)
        inception_4b_double_3x3_1_out = self.inception_4b_double_3x3_1(inception_4b_relu_double_3x3_reduce_out)
        inception_4b_double_3x3_1_bn_out = self.inception_4b_double_3x3_1_bn(inception_4b_double_3x3_1_out)
        inception_4b_relu_double_3x3_1_out = self.inception_4b_relu_double_3x3_1(inception_4b_double_3x3_1_bn_out)
        inception_4b_double_3x3_2_out = self.inception_4b_double_3x3_2(inception_4b_relu_double_3x3_1_out)
        inception_4b_double_3x3_2_bn_out = self.inception_4b_double_3x3_2_bn(inception_4b_double_3x3_2_out)
        inception_4b_relu_double_3x3_2_out = self.inception_4b_relu_double_3x3_2(inception_4b_double_3x3_2_bn_out)
        inception_4b_pool_out = self.inception_4b_pool(inception_4a_output_out)
        inception_4b_pool_proj_out = self.inception_4b_pool_proj(inception_4b_pool_out)
        inception_4b_pool_proj_bn_out = self.inception_4b_pool_proj_bn(inception_4b_pool_proj_out)
        inception_4b_relu_pool_proj_out = self.inception_4b_relu_pool_proj(inception_4b_pool_proj_bn_out)
        inception_4b_output_out = torch.cat([inception_4b_relu_1x1_out,inception_4b_relu_3x3_out,inception_4b_relu_double_3x3_2_out,inception_4b_relu_pool_proj_out], 1)
        inception_4c_1x1_out = self.inception_4c_1x1(inception_4b_output_out)
        inception_4c_1x1_bn_out = self.inception_4c_1x1_bn(inception_4c_1x1_out)
        inception_4c_relu_1x1_out = self.inception_4c_relu_1x1(inception_4c_1x1_bn_out)
        inception_4c_3x3_reduce_out = self.inception_4c_3x3_reduce(inception_4b_output_out)
        inception_4c_3x3_reduce_bn_out = self.inception_4c_3x3_reduce_bn(inception_4c_3x3_reduce_out)
        inception_4c_relu_3x3_reduce_out = self.inception_4c_relu_3x3_reduce(inception_4c_3x3_reduce_bn_out)
        inception_4c_3x3_out = self.inception_4c_3x3(inception_4c_relu_3x3_reduce_out)
        inception_4c_3x3_bn_out = self.inception_4c_3x3_bn(inception_4c_3x3_out)
        inception_4c_relu_3x3_out = self.inception_4c_relu_3x3(inception_4c_3x3_bn_out)
        inception_4c_double_3x3_reduce_out = self.inception_4c_double_3x3_reduce(inception_4b_output_out)
        inception_4c_double_3x3_reduce_bn_out = self.inception_4c_double_3x3_reduce_bn(inception_4c_double_3x3_reduce_out)
        inception_4c_relu_double_3x3_reduce_out = self.inception_4c_relu_double_3x3_reduce(inception_4c_double_3x3_reduce_bn_out)
        inception_4c_double_3x3_1_out = self.inception_4c_double_3x3_1(inception_4c_relu_double_3x3_reduce_out)
        inception_4c_double_3x3_1_bn_out = self.inception_4c_double_3x3_1_bn(inception_4c_double_3x3_1_out)
        inception_4c_relu_double_3x3_1_out = self.inception_4c_relu_double_3x3_1(inception_4c_double_3x3_1_bn_out)
        inception_4c_double_3x3_2_out = self.inception_4c_double_3x3_2(inception_4c_relu_double_3x3_1_out)
        inception_4c_double_3x3_2_bn_out = self.inception_4c_double_3x3_2_bn(inception_4c_double_3x3_2_out)
        inception_4c_relu_double_3x3_2_out = self.inception_4c_relu_double_3x3_2(inception_4c_double_3x3_2_bn_out)
        inception_4c_pool_out = self.inception_4c_pool(inception_4b_output_out)
        inception_4c_pool_proj_out = self.inception_4c_pool_proj(inception_4c_pool_out)
        inception_4c_pool_proj_bn_out = self.inception_4c_pool_proj_bn(inception_4c_pool_proj_out)
        inception_4c_relu_pool_proj_out = self.inception_4c_relu_pool_proj(inception_4c_pool_proj_bn_out)
        inception_4c_output_out = torch.cat([inception_4c_relu_1x1_out,inception_4c_relu_3x3_out,inception_4c_relu_double_3x3_2_out,inception_4c_relu_pool_proj_out], 1)
        inception_4d_1x1_out = self.inception_4d_1x1(inception_4c_output_out)
        inception_4d_1x1_bn_out = self.inception_4d_1x1_bn(inception_4d_1x1_out)
        inception_4d_relu_1x1_out = self.inception_4d_relu_1x1(inception_4d_1x1_bn_out)
        inception_4d_3x3_reduce_out = self.inception_4d_3x3_reduce(inception_4c_output_out)
        inception_4d_3x3_reduce_bn_out = self.inception_4d_3x3_reduce_bn(inception_4d_3x3_reduce_out)
        inception_4d_relu_3x3_reduce_out = self.inception_4d_relu_3x3_reduce(inception_4d_3x3_reduce_bn_out)
        inception_4d_3x3_out = self.inception_4d_3x3(inception_4d_relu_3x3_reduce_out)
        inception_4d_3x3_bn_out = self.inception_4d_3x3_bn(inception_4d_3x3_out)
        inception_4d_relu_3x3_out = self.inception_4d_relu_3x3(inception_4d_3x3_bn_out)
        inception_4d_double_3x3_reduce_out = self.inception_4d_double_3x3_reduce(inception_4c_output_out)
        inception_4d_double_3x3_reduce_bn_out = self.inception_4d_double_3x3_reduce_bn(inception_4d_double_3x3_reduce_out)
        inception_4d_relu_double_3x3_reduce_out = self.inception_4d_relu_double_3x3_reduce(inception_4d_double_3x3_reduce_bn_out)
        inception_4d_double_3x3_1_out = self.inception_4d_double_3x3_1(inception_4d_relu_double_3x3_reduce_out)
        inception_4d_double_3x3_1_bn_out = self.inception_4d_double_3x3_1_bn(inception_4d_double_3x3_1_out)
        inception_4d_relu_double_3x3_1_out = self.inception_4d_relu_double_3x3_1(inception_4d_double_3x3_1_bn_out)
        inception_4d_double_3x3_2_out = self.inception_4d_double_3x3_2(inception_4d_relu_double_3x3_1_out)
        inception_4d_double_3x3_2_bn_out = self.inception_4d_double_3x3_2_bn(inception_4d_double_3x3_2_out)
        inception_4d_relu_double_3x3_2_out = self.inception_4d_relu_double_3x3_2(inception_4d_double_3x3_2_bn_out)
        inception_4d_pool_out = self.inception_4d_pool(inception_4c_output_out)
        inception_4d_pool_proj_out = self.inception_4d_pool_proj(inception_4d_pool_out)
        inception_4d_pool_proj_bn_out = self.inception_4d_pool_proj_bn(inception_4d_pool_proj_out)
        inception_4d_relu_pool_proj_out = self.inception_4d_relu_pool_proj(inception_4d_pool_proj_bn_out)
        inception_4d_output_out = torch.cat([inception_4d_relu_1x1_out,inception_4d_relu_3x3_out,inception_4d_relu_double_3x3_2_out,inception_4d_relu_pool_proj_out], 1)
        inception_4e_3x3_reduce_out = self.inception_4e_3x3_reduce(inception_4d_output_out)
        inception_4e_3x3_reduce_bn_out = self.inception_4e_3x3_reduce_bn(inception_4e_3x3_reduce_out)
        inception_4e_relu_3x3_reduce_out = self.inception_4e_relu_3x3_reduce(inception_4e_3x3_reduce_bn_out)
        inception_4e_3x3_out = self.inception_4e_3x3(inception_4e_relu_3x3_reduce_out)
        inception_4e_3x3_bn_out = self.inception_4e_3x3_bn(inception_4e_3x3_out)
        inception_4e_relu_3x3_out = self.inception_4e_relu_3x3(inception_4e_3x3_bn_out)
        inception_4e_double_3x3_reduce_out = self.inception_4e_double_3x3_reduce(inception_4d_output_out)
        inception_4e_double_3x3_reduce_bn_out = self.inception_4e_double_3x3_reduce_bn(inception_4e_double_3x3_reduce_out)
        inception_4e_relu_double_3x3_reduce_out = self.inception_4e_relu_double_3x3_reduce(inception_4e_double_3x3_reduce_bn_out)
        inception_4e_double_3x3_1_out = self.inception_4e_double_3x3_1(inception_4e_relu_double_3x3_reduce_out)
        inception_4e_double_3x3_1_bn_out = self.inception_4e_double_3x3_1_bn(inception_4e_double_3x3_1_out)
        inception_4e_relu_double_3x3_1_out = self.inception_4e_relu_double_3x3_1(inception_4e_double_3x3_1_bn_out)
        inception_4e_double_3x3_2_out = self.inception_4e_double_3x3_2(inception_4e_relu_double_3x3_1_out)
        inception_4e_double_3x3_2_bn_out = self.inception_4e_double_3x3_2_bn(inception_4e_double_3x3_2_out)
        inception_4e_relu_double_3x3_2_out = self.inception_4e_relu_double_3x3_2(inception_4e_double_3x3_2_bn_out)
        inception_4e_pool_out = self.inception_4e_pool(inception_4d_output_out)
        inception_4e_output_out = torch.cat([inception_4e_relu_3x3_out,inception_4e_relu_double_3x3_2_out,inception_4e_pool_out], 1)
        inception_5a_1x1_out = self.inception_5a_1x1(inception_4e_output_out)
        inception_5a_1x1_bn_out = self.inception_5a_1x1_bn(inception_5a_1x1_out)
        inception_5a_relu_1x1_out = self.inception_5a_relu_1x1(inception_5a_1x1_bn_out)
        inception_5a_3x3_reduce_out = self.inception_5a_3x3_reduce(inception_4e_output_out)
        inception_5a_3x3_reduce_bn_out = self.inception_5a_3x3_reduce_bn(inception_5a_3x3_reduce_out)
        inception_5a_relu_3x3_reduce_out = self.inception_5a_relu_3x3_reduce(inception_5a_3x3_reduce_bn_out)
        inception_5a_3x3_out = self.inception_5a_3x3(inception_5a_relu_3x3_reduce_out)
        inception_5a_3x3_bn_out = self.inception_5a_3x3_bn(inception_5a_3x3_out)
        inception_5a_relu_3x3_out = self.inception_5a_relu_3x3(inception_5a_3x3_bn_out)
        inception_5a_double_3x3_reduce_out = self.inception_5a_double_3x3_reduce(inception_4e_output_out)
        inception_5a_double_3x3_reduce_bn_out = self.inception_5a_double_3x3_reduce_bn(inception_5a_double_3x3_reduce_out)
        inception_5a_relu_double_3x3_reduce_out = self.inception_5a_relu_double_3x3_reduce(inception_5a_double_3x3_reduce_bn_out)
        inception_5a_double_3x3_1_out = self.inception_5a_double_3x3_1(inception_5a_relu_double_3x3_reduce_out)
        inception_5a_double_3x3_1_bn_out = self.inception_5a_double_3x3_1_bn(inception_5a_double_3x3_1_out)
        inception_5a_relu_double_3x3_1_out = self.inception_5a_relu_double_3x3_1(inception_5a_double_3x3_1_bn_out)
        inception_5a_double_3x3_2_out = self.inception_5a_double_3x3_2(inception_5a_relu_double_3x3_1_out)
        inception_5a_double_3x3_2_bn_out = self.inception_5a_double_3x3_2_bn(inception_5a_double_3x3_2_out)
        inception_5a_relu_double_3x3_2_out = self.inception_5a_relu_double_3x3_2(inception_5a_double_3x3_2_bn_out)
        inception_5a_pool_out = self.inception_5a_pool(inception_4e_output_out)
        inception_5a_pool_proj_out = self.inception_5a_pool_proj(inception_5a_pool_out)
        inception_5a_pool_proj_bn_out = self.inception_5a_pool_proj_bn(inception_5a_pool_proj_out)
        inception_5a_relu_pool_proj_out = self.inception_5a_relu_pool_proj(inception_5a_pool_proj_bn_out)
        inception_5a_output_out = torch.cat([inception_5a_relu_1x1_out,inception_5a_relu_3x3_out,inception_5a_relu_double_3x3_2_out,inception_5a_relu_pool_proj_out], 1)
        inception_5b_1x1_out = self.inception_5b_1x1(inception_5a_output_out)
        inception_5b_1x1_bn_out = self.inception_5b_1x1_bn(inception_5b_1x1_out)
        inception_5b_relu_1x1_out = self.inception_5b_relu_1x1(inception_5b_1x1_bn_out)
        inception_5b_3x3_reduce_out = self.inception_5b_3x3_reduce(inception_5a_output_out)
        inception_5b_3x3_reduce_bn_out = self.inception_5b_3x3_reduce_bn(inception_5b_3x3_reduce_out)
        inception_5b_relu_3x3_reduce_out = self.inception_5b_relu_3x3_reduce(inception_5b_3x3_reduce_bn_out)
        inception_5b_3x3_out = self.inception_5b_3x3(inception_5b_relu_3x3_reduce_out)
        inception_5b_3x3_bn_out = self.inception_5b_3x3_bn(inception_5b_3x3_out)
        inception_5b_relu_3x3_out = self.inception_5b_relu_3x3(inception_5b_3x3_bn_out)
        inception_5b_double_3x3_reduce_out = self.inception_5b_double_3x3_reduce(inception_5a_output_out)
        inception_5b_double_3x3_reduce_bn_out = self.inception_5b_double_3x3_reduce_bn(inception_5b_double_3x3_reduce_out)
        inception_5b_relu_double_3x3_reduce_out = self.inception_5b_relu_double_3x3_reduce(inception_5b_double_3x3_reduce_bn_out)
        inception_5b_double_3x3_1_out = self.inception_5b_double_3x3_1(inception_5b_relu_double_3x3_reduce_out)
        inception_5b_double_3x3_1_bn_out = self.inception_5b_double_3x3_1_bn(inception_5b_double_3x3_1_out)
        inception_5b_relu_double_3x3_1_out = self.inception_5b_relu_double_3x3_1(inception_5b_double_3x3_1_bn_out)
        inception_5b_double_3x3_2_out = self.inception_5b_double_3x3_2(inception_5b_relu_double_3x3_1_out)
        inception_5b_double_3x3_2_bn_out = self.inception_5b_double_3x3_2_bn(inception_5b_double_3x3_2_out)
        inception_5b_relu_double_3x3_2_out = self.inception_5b_relu_double_3x3_2(inception_5b_double_3x3_2_bn_out)
        inception_5b_pool_out = self.inception_5b_pool(inception_5a_output_out)
        inception_5b_pool_proj_out = self.inception_5b_pool_proj(inception_5b_pool_out)
        inception_5b_pool_proj_bn_out = self.inception_5b_pool_proj_bn(inception_5b_pool_proj_out)
        inception_5b_relu_pool_proj_out = self.inception_5b_relu_pool_proj(inception_5b_pool_proj_bn_out)
        inception_5b_output_out = torch.cat([inception_5b_relu_1x1_out,inception_5b_relu_3x3_out,inception_5b_relu_double_3x3_2_out,inception_5b_relu_pool_proj_out], 1)
        return inception_5b_output_out

    def logits(self, x):
        x = F.adaptive_avg_pool2d(x, (1, 1))
        x = x.view(x.size(0), -1)
        if self.last_linear:
            x = self.last_linear(x)
        return x

    def forward(self, x):
        x = self.features(x)
        x = self.logits(x)
        return x


def bninception(pretrained=False, **kwargs):
    r"""BNInception model architecture from <https://arxiv.org/pdf/1502.03167.pdf>`_ paper.
    """
    model = BNInception(**kwargs)
    if pretrained:
        state_dict = load_url(model_urls['bninception'])
        # convert weights from BGR to RGB mode
        state_dict['conv1_7x7_s2.weight'] = \
            state_dict['conv1_7x7_s2.weight'][:, [2, 1, 0], :, :]
        # check num_classes
        if model.last_linear is None or state_dict[
            'last_linear.weight'].size(0) != model.num_classes:
            state_dict.pop('last_linear.weight')
            state_dict.pop('last_linear.bias')
        # load state_dict
        model.load_state_dict(state_dict, strict=True)
    return model
